[package]
name = "gst"
version = "0.1.0"
authors = ["mbila"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gstreamer = "*"
byte-slice-cast = "*"
gstreamer-video = "*"