[package]
name = "async_chat"
version = "0.1.0"
authors = ["Muhammad Hassan <hassanmuhammad221@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.7"
async-std = "1.6.5"
